name: docs

on:
  push:
    branches:
    - master
    - develop
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Setup
        run: |
          python -m pip install tox tox-gh-actions
      - name: Build docs
        run: |
          tox -e docs -- --publish --branches ${{ steps.extract_branch.outputs.branch }}
