name: tests

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  test:
    strategy:
      matrix:
        python: [3.6, 3.9]
        platform: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install SuperCollider
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update --yes
              sudo apt-get install --yes --reinstall qt5-default qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev libqt5svg5-dev libqt5websockets5-dev qtwebengine5-dev
              sudo apt-get install --yes --reinstall supercollider libsndfile1 libavahi-client-dev libfftw3-dev libicu-dev libudev-dev jackd1 libxcb1 libxcb-xinerama0
              # start jack
              jackd --no-realtime -d dummy &
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install --cask supercollider
          elif [ "$RUNNER_OS" == "Windows" ]; then
              # choco only offers an ancient version of SC.
              choco install supercollider
          fi
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run tests
        env:
          QT_DEBUG_PLUGINS: 1
          QT_QPA_PLATFORM_PLUGIN_PATH: '/usr/lib/x86_64-linux-gnu/qt5/plugins'
        run: tox
