name: tests

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  test:
    strategy:
      matrix:
        python:
        - 3.6
        - 3.9
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install SuperCollider
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install supercollider
              # start jack
              jackd --no-realtime -d dummy &
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install --cask supercollider
          elif [ "$RUNNER_OS" == "Windows" ]; then
              # choco only offers an ancient version of SC.
              choco install supercollider
          fi
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run tests on macOS/Windows
        if: runner.os != 'Linux'
        run: tox
      - name: Run tests on Linux
        if: runner.os == 'Linux'
        run: xvfb-run --server-args="-screen 0, 1280x720x24" -a tox
