name: tests

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  test:
    strategy:
      matrix:
        python:
        - 3.6
        - 3.9
        - 3.10.0-alpha - 3.10.99
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install SuperCollider
        # choco only offers an ancient version of SC.
        run: |
          #!/bin/bash -eE
          :<<"::batch"
          choco install supercollider
          goto :end
          ::batch
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt install supercollider
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install --cask supercollider
          fi
          exit $?
          :<<"::done"
          :end
          ::done
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run tests
        run: tox
